Repository Team-PWP/Swap_FE, pull requests merged in 2024-05, with the labels that each got.

#2 추가 환경 세팅
  .eslintrc.json
  .prettierrc.json
  index.html
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/constants/URI.ts
  src/main.tsx
  src/pages/login/LoginPage.tsx
  src/pages/product/MyProductPage.tsx
  src/pages/product/UserProductPage.tsx
  src/router.tsx
  tsconfig.json
Labels: 📦 Environment

#10 로그인 페이지 구현
  .prettierrc.json
  package.json
  pnpm-lock.yaml
  src/apis/.gitkeep
  src/apis/OAuth.ts
  src/assets/.gitkeep
  src/assets/kakao.svg
  src/components/.gitkeep
  src/components/header/index.tsx
  src/constants/URI.ts
  src/hooks/.gitkeep
  src/hooks/useOauth2Redirect.ts
  src/pages/login/LoginPage.tsx
  src/pages/login/RedirectPage.tsx
  src/pages/login/index.tsx
  src/pages/login/styles.ts
  src/pages/nickname/NickNamePage.tsx
  src/router.tsx
  src/store/.gitkeep
  src/store/useAuthStore.ts
  tsconfig.json
  vite.config.ts
Labels: ✨ Feature, 📦 Environment, 📬 API

#12 헤더 및 검색창 구현
  index.html
  public/Logo.svg
  src/assets/Chatting-Icon.svg
  src/assets/Product-Icon.svg
  src/assets/Search-Icon.svg
  src/assets/Sell-Icon.svg
  src/assets/Swap-Logo.svg
  src/components/header/Layout/BottomHeaderLayout.tsx
  src/components/header/Layout/HeaderLayout.tsx
  src/components/header/Layout/Inner.tsx
  src/components/header/Layout/Logo.tsx
  src/components/header/Layout/NavItem.tsx
  src/components/header/Layout/SearchLayout.tsx
  src/components/header/Layout/TopHeaderLayout.tsx
  src/components/header/styles.ts
  src/components/header/type.ts
Labels: ✨ Feature

#18 MainPage 구현 및 공통 css 구현
  src/App.tsx
  src/assets/Emoji-Button.svg
  src/assets/Send-Button.svg
  src/pages/MainPage.tsx
  src/pages/main/components/FreeMarket.tsx
  src/pages/main/index.tsx
  src/pages/main/styles.ts
  src/pages/main/type.ts
  src/router.tsx
  src/styles/GlobalStyle.ts
  src/styles/PcLayout.ts
Labels: 📝 Docs, ✨ Feature

#21 MainPage 구현
  src/pages/main/components/MainProduct.tsx
  src/pages/main/components/ProductItem.tsx
  src/pages/main/index.tsx
  src/pages/main/styles.ts
  src/styles/TitleStyle.tsx
Labels: ✨ Feature, 💄 Design

#33 Feat/issue 27
  package-lock.json
  package.json
  src/components/chat/ChatBottom.tsx
  src/components/chat/ChatInput.tsx
  src/components/header/Layout/BottomHeaderLayout.tsx
  src/pages/chatting/ChatTestPage.tsx
  src/pages/chatting/ChattingPage.tsx
  src/pages/main/index.tsx
  src/router.tsx
  src/store/useRoomInfoStore.ts
  vite.config.ts
Labels: ✨ Feature, 📬 API

#38 Feat/issue 36
  src/apis/chat/chatlog.api.ts
  src/apis/chat/chatlog.request.ts
  src/apis/chat/chatroom.api.ts
  src/apis/chat/chatroom.request.ts
  src/apis/wish/wish.api.ts
  src/apis/wish/wish.request.ts
  src/components/wish/Wish.tsx
  src/pages/chatlist/ChatlistPage.tsx
  src/pages/chatting/ChattingPage.tsx
  src/pages/main/index.tsx
  src/pages/wish/WishListPage.tsx
  src/router.tsx
Labels: ✨ Feature, 📬 API, 💄 Design

#39 Feat/issue 34
  src/pages/chatlist/ChatlistPage.tsx
  src/pages/chatting/ChattingPage.tsx
  src/router.tsx
Labels: ✨ Feature, 📬 API, 💄 Design

#40 Feat/issue 37
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/apis/bid/bid.api.ts
  src/apis/bid/bid.request.ts
  src/components/bid/BiddingModal.tsx
  src/pages/detail/components/UploadInfo.tsx
Labels: ✨ Feature, 📬 API, 💄 Design

#43 페이지 이동 기능 구현
  package.json
  pnpm-lock.yaml
  src/pages/main/components/AllProduct.tsx
  src/pages/main/components/MainProduct.tsx
  src/pages/main/components/page.css
  src/pages/main/styles.ts
  src/store/usePageStore.ts
Labels: ✨ Feature, 📬 API

#46 page 기능 수정
  src/pages/main/components/MainProduct.tsx
Labels: 😡 BugFix

#49 Feat/issue 48
  src/apis/chat/chatroom.api.ts
  src/apis/chat/chatroom.request.ts
  src/apis/detail/detail.api.ts
  src/apis/detail/detail.request.ts
  src/components/chat/ChatCreateModal.tsx
  src/components/header/Layout/BottomHeaderLayout.tsx
  src/pages/chatlist/ChatlistPage.tsx
  src/pages/chatting/ChattingPage.tsx
  src/pages/detail/components/ProductDetail.tsx
  src/pages/detail/components/UploadInfo.tsx
  src/pages/wish/WishListPage.tsx
  src/store/useProductSellStore.ts
  src/store/useUserInfoStore.ts
Labels: ✨ Feature, 📬 API, 💄 Design

#54 Design/issue 50
  package.json
  pnpm-lock.yaml
  src/components/chat/ChatBox.tsx
  src/components/chat/ChatInput.tsx
  src/components/chatlist/ChatRoom.tsx
  src/pages/chatlist/ChatlistPage.tsx
  src/pages/chatting/ChattingPage.tsx
  src/styles/GlobalLayout.tsx
Labels: ✨ Feature, 📬 API, 💄 Design

#55 Feat/issue 52
  package.json
  pnpm-lock.yaml
  src/components/chat/ChatBox.tsx
  src/components/chat/ChatHead.tsx
  src/pages/chatlist/ChatlistPage.tsx
  src/pages/detail/index.tsx
  src/pages/main/components/FreeMarket.tsx
  src/pages/main/index.tsx
  src/pages/main/styles.ts
  src/store/useUserInfoStore.ts
  src/styles/TitleStyle.ts
Labels: ✨ Feature, 📬 API, 💄 Design

#57 Feat/issue 56
  src/apis/search/search.api.ts
  src/apis/search/search.request.ts
  src/components/bid/BiddingModal.tsx
  src/components/chat/ChatCreateModal.tsx
  src/components/chat/ChatHead.tsx
  src/components/chat/OpenChatBox.tsx
  src/components/header/Layout/SearchLayout.tsx
  src/components/header/styles.ts
  src/pages/chatting/ChattingPage.tsx
  src/pages/main/components/FreeMarket.tsx
  src/pages/main/components/MainProduct.tsx
  src/styles/GlobalLayout.tsx
Labels: ✨ Feature, 📬 API, 💄 Design

#59 feat: myStore api 구현
  src/apis/mystore/mystore.api.ts
  src/apis/mystore/mystore.request.ts
  src/pages/shop/index.tsx
Labels: ✨ Feature, 📬 API, 💄 Design

#61 Feat/issue 60
  src/components/bid/MaxpriceBidModal.tsx
  src/pages/chatlist/ChatlistPage.tsx
  src/pages/detail/components/ProductDetail.tsx
  src/pages/detail/components/UploadInfo.tsx
  src/pages/wish/WishListPage.tsx
  src/store/useBuyoutStore.ts
Labels: ✨ Feature, 📬 API, 💄 Design
